FROM elasticsearch:1.4

RUN /usr/share/elasticsearch/bin/plugin -install analysis-morphology -url http://dl.bintray.com/content/imotov/elasticsearch-plugins/org/elasticsearch/elasticsearch-analysis-morphology/1.2.0/elasticsearch-analysis-morphology-1.2.0.zip
RUN /usr/share/elasticsearch/bin/plugin -install mobz/elasticsearch-head
